### ISSUE TITLE
Fix regression tests on CUDA and ROCm

### ISSUE THREAD

**Issue by jakki-amd** [nod-ai/serve#23]
Fix regression tests

**Comment by eppane** [comment]
Appended the [comment](https://github.com/nod-ai/serve/pull/5#issue-2652214621) in pull request #5:

OBS! The [test](https://github.com/nod-ai/serve/blob/master/test/pytest/test_handler.py#L361) `test_handler.py::test_huggingface_bert_model_parallel_inference` fails due to:

```ValueError: Input length of input_ids is 150, but max_length is set to 50. This can lead to unexpected behavior. You should consider increasing max_length or, better yet, setting max_new_tokens.```

This indicates that preprocessing uses a different `max_length` than inference, which can be verified when looking at the handler when the test was originally implemented: [model.generate()](https://github.com/nod-ai/serve/blob/4c67d97173c72ec6b6cd4050713fd066ace698aa/examples/Huggingface_Transformers/Transformer_handler_generalized.py#L244) has `max_length=50` by default, while [tokenizer uses max_length](https://github.com/nod-ai/serve/blob/4c67d97173c72ec6b6cd4050713fd066ace698aa/examples/Huggingface_Transformers/Transformer_handler_generalized.py#L140-L144) from [setup_config](https://github.com/nod-ai/serve/blob/4c67d97173c72ec6b6cd4050713fd066ace698aa/examples/Huggingface_Transformers/setup_config.json#L7) (`max_length=150`). It seems that the bert-based `Textgeneration.mar` needs an update.
